import React, { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { ShoppingBag, Search, Heart, Menu, X, Star, ShieldCheck, Truck, CreditCard, Package, Users, Bell, BarChart3, Plus, Minus, Trash2, Play, ArrowRight, Mail, Phone, MapPin, DollarSign, ClipboardList, Save, Send, User, Lock } from "lucide-react";

const logoImage = "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=160&q=80";
const adminEmail = "admin@aurelia.com";
const adminPassword = "Admin@123";
const demoUserEmail = "user@aurelia.com";
const demoUserPassword = "User@123";

const starterProducts = [
  { id: 1, name: "Classic Wool Coat", category: "Women", price: 220, oldPrice: 280, rating: 4.9, stock: 20, badge: "Best Seller", image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80" },
  { id: 2, name: "Premium Leather Bag", category: "Accessories", price: 165, oldPrice: 210, rating: 4.8, stock: 16, badge: "New", image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80" },
  { id: 3, name: "Tailored Black Suit", category: "Men", price: 310, oldPrice: 390, rating: 4.9, stock: 10, badge: "Luxury", image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80" },
  { id: 4, name: "Silk Evening Dress", category: "Women", price: 260, oldPrice: 340, rating: 5.0, stock: 8, badge: "Premium", image: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=900&q=80" },
  { id: 5, name: "Minimal White Sneakers", category: "Shoes", price: 120, oldPrice: 155, rating: 4.7, stock: 25, badge: "Popular", image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80" },
  { id: 6, name: "Gold Detail Watch", category: "Accessories", price: 195, oldPrice: 250, rating: 4.8, stock: 14, badge: "Classic", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80" },
];

const categories = ["All", "Women", "Men", "Shoes", "Accessories"];
const currency = (value) => `$${Number(value || 0).toLocaleString()}`;

export default function App() {
  const [view, setView] = useState("home");
  const [menuOpen, setMenuOpen] = useState(false);
  const [authMode, setAuthMode] = useState("login");
  const [currentUser, setCurrentUser] = useState(null);
  const [authError, setAuthError] = useState("");
  const [activeCategory, setActiveCategory] = useState("All");
  const [query, setQuery] = useState("");
  const [products, setProducts] = useState(starterProducts);
  const [cart, setCart] = useState([]);
  const [wishlist, setWishlist] = useState([]);
  const [customer, setCustomer] = useState({ name: "Hasnain Akram", email: "hasnain@example.com", phone: "+92 300 0000000", city: "Jhang", area: "Civil Lines", street: "House #12, Main Road", zip: "35200", country: "Pakistan" });

  const filteredProducts = useMemo(() => products.filter((p) => (activeCategory === "All" || p.category === activeCategory) && p.name.toLowerCase().includes(query.toLowerCase())), [products, activeCategory, query]);
  const cartTotal = cart.reduce((sum, item) => sum + Number(item.price) * item.qty, 0);
  const revenue = products.reduce((sum, p) => sum + Number(p.price) * Math.max(1, Number(p.stock)), 0);

  const addToCart = (product) => setCart((items) => {
    const exists = items.find((item) => item.id === product.id);
    return exists ? items.map((item) => item.id === product.id ? { ...item, qty: item.qty + 1 } : item) : [...items, { ...product, qty: 1, size: "M", color: "Black" }];
  });
  const changeQty = (id, delta) => setCart((items) => items.map((item) => item.id === id ? { ...item, qty: Math.max(1, item.qty + delta) } : item));
  const removeFromCart = (id) => setCart((items) => items.filter((item) => item.id !== id));
  const toggleWishlist = (product) => setWishlist((items) => items.find((i) => i.id === product.id) ? items.filter((i) => i.id !== product.id) : [...items, product]);
  const addProduct = (product) => setProducts((items) => [{ ...product, id: Date.now(), rating: 4.8, oldPrice: Number(product.price) + 45 }, ...items]);
  const deleteProduct = (id) => setProducts((items) => items.filter((p) => p.id !== id));

  const handleAuth = (form) => {
    setAuthError("");
    if (!form.email || !form.password) return setAuthError("Email and password are required.");
    if (authMode === "signup") {
      if (!form.name || !form.phone) return setAuthError("Name, phone, email and password are required.");
      setCurrentUser({ name: form.name, email: form.email, role: "customer" });
      setCustomer({ ...customer, name: form.name, email: form.email, phone: form.phone });
      setView("dashboard");
      return;
    }
    if (form.email === adminEmail && form.password === adminPassword) {
      setCurrentUser({ name: "Admin", email: adminEmail, role: "admin" });
      setView("admin");
      return;
    }
    if (form.email === demoUserEmail && form.password === demoUserPassword) {
      setCurrentUser({ name: "Demo User", email: demoUserEmail, role: "customer" });
      setView("dashboard");
      return;
    }
    setAuthError("Invalid email/password. Use admin@aurelia.com / Admin@123 or user@aurelia.com / User@123");
  };

  const logout = () => { setCurrentUser(null); setView("home"); };

  return (
    <main className="min-h-screen bg-[#f8f4ee] text-[#171411]">
      <Header menuOpen={menuOpen} setMenuOpen={setMenuOpen} cartCount={cart.reduce((s, i) => s + i.qty, 0)} wishlistCount={wishlist.length} setView={setView} currentUser={currentUser} logout={logout} />
      {view === "home" && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}><Hero setView={setView} /><TrustBar /><VideoSection /><Collections /><Shop products={filteredProducts} activeCategory={activeCategory} setActiveCategory={setActiveCategory} query={query} setQuery={setQuery} addToCart={addToCart} toggleWishlist={toggleWishlist} wishlist={wishlist} /><ClassicBanner /><Testimonials /><ContactSection customer={customer} /><Newsletter /><Footer /></motion.div>}
      {view === "auth" && <AuthPage authMode={authMode} setAuthMode={setAuthMode} handleAuth={handleAuth} authError={authError} />}
      {view === "cart" && <CartPage cart={cart} cartTotal={cartTotal} changeQty={changeQty} removeFromCart={removeFromCart} setView={setView} customer={customer} />}
      {view === "dashboard" && (currentUser ? <CustomerDashboard wishlist={wishlist} cart={cart} customer={customer} setCustomer={setCustomer} currentUser={currentUser} /> : <AuthPage authMode={authMode} setAuthMode={setAuthMode} handleAuth={handleAuth} authError={authError} />)}
      {view === "admin" && (currentUser?.role === "admin" ? <AdminDashboard products={products} deleteProduct={deleteProduct} addProduct={addProduct} revenue={revenue} customer={customer} /> : <AdminLoginRequired setView={setView} setAuthMode={setAuthMode} />)}
    </main>
  );
}

function Header({ menuOpen, setMenuOpen, cartCount, wishlistCount, setView, currentUser, logout }) {
  const nav = [["Home", "home"], ["Shop", "home"], ["Customer", "dashboard"], ["Admin", "admin"]];
  return <header className="sticky top-0 z-50 border-b border-[#ded4c5] bg-[#f8f4ee]/95 px-4 py-4 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between"><button onClick={() => setView("home")} className="flex items-center gap-3"><img src={logoImage} alt="Store logo" className="h-12 w-12 rounded-full object-cover ring-2 ring-[#171411]" /><div className="text-left"><h1 className="text-xl font-serif font-black tracking-wide">AURELIA</h1><p className="text-xs uppercase tracking-[0.25em] text-[#7a6b5b]">Classic Store</p></div></button><nav className="hidden items-center gap-7 md:flex">{nav.map(([label, target]) => <button key={label} onClick={() => setView(target)} className="text-sm font-semibold uppercase tracking-[0.18em] text-[#4b4138] hover:text-black">{label}</button>)}</nav><div className="flex items-center gap-2"><button className="relative rounded-full border border-[#d4c7b6] bg-white p-3"><Heart className="h-4 w-4" />{wishlistCount > 0 && <Count>{wishlistCount}</Count>}</button><button onClick={() => setView("cart")} className="relative rounded-full border border-[#d4c7b6] bg-white p-3"><ShoppingBag className="h-4 w-4" />{cartCount > 0 && <Count>{cartCount}</Count>}</button>{currentUser ? <button onClick={logout} className="hidden rounded-full border border-[#d4c7b6] bg-white px-4 py-3 text-sm font-bold md:block">Logout</button> : <button onClick={() => setView("auth")} className="hidden rounded-full bg-[#171411] px-5 py-3 text-sm font-bold text-white md:block">Login</button>}<button onClick={() => setMenuOpen(!menuOpen)} className="rounded-full border border-[#d4c7b6] bg-white p-3 md:hidden">{menuOpen ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}</button></div></div>{menuOpen && <div className="mx-auto mt-4 grid max-w-7xl gap-2 rounded-3xl border border-[#d4c7b6] bg-white p-3 shadow-xl md:hidden">{nav.map(([label, target]) => <button key={label} onClick={() => { setView(target); setMenuOpen(false); }} className="rounded-2xl px-4 py-3 text-left font-semibold hover:bg-[#f8f4ee]">{label}</button>)}{currentUser ? <button onClick={() => { logout(); setMenuOpen(false); }} className="rounded-2xl px-4 py-3 text-left font-semibold hover:bg-[#f8f4ee]">Logout</button> : <button onClick={() => { setView("auth"); setMenuOpen(false); }} className="rounded-2xl bg-[#171411] px-4 py-3 text-left font-semibold text-white">Login / Signup</button>}</div>}</header>;
}
function Count({ children }) { return <span className="absolute -right-1 -top-1 grid h-5 w-5 place-items-center rounded-full bg-[#171411] text-xs text-white">{children}</span>; }

function AuthPage({ authMode, setAuthMode, handleAuth, authError }) {
  const [form, setForm] = useState({ name: "", phone: "", email: "", password: "" });
  const isSignup = authMode === "signup";
  return <motion.section initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mx-auto min-h-[80vh] max-w-5xl px-4 py-16"><div className="grid overflow-hidden rounded-[2rem] border border-[#d4c7b6] bg-white shadow-xl lg:grid-cols-2"><img src="https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1000&q=80" alt="Login" className="hidden h-full w-full object-cover lg:block" /><div className="p-8 md:p-12"><p className="text-sm font-bold uppercase tracking-[0.3em] text-[#8b745d]">Authentication</p><h2 className="mt-3 font-serif text-5xl font-black">{isSignup ? "Create account" : "Login account"}</h2><p className="mt-4 text-sm leading-7 text-[#5f5349]">Admin: <b>{adminEmail}</b> / <b>{adminPassword}</b><br />User: <b>{demoUserEmail}</b> / <b>{demoUserPassword}</b></p><form onSubmit={(e) => { e.preventDefault(); handleAuth(form); }} className="mt-7 grid gap-4">{isSignup && <><Input label="Full Name *" value={form.name} onChange={(v) => setForm({ ...form, name: v })} /><Input label="Phone Number *" value={form.phone} onChange={(v) => setForm({ ...form, phone: v })} /></>}<Input label="Email Address *" type="email" value={form.email} onChange={(v) => setForm({ ...form, email: v })} /><Input label="Password *" type="password" value={form.password} onChange={(v) => setForm({ ...form, password: v })} />{authError && <div className="rounded-2xl bg-red-100 p-4 text-sm font-bold text-red-700">{authError}</div>}<button className="inline-flex items-center justify-center gap-2 rounded-full bg-[#171411] px-6 py-4 font-bold text-white"><Lock className="h-4 w-4" />{isSignup ? "Sign Up" : "Login"}</button></form><button onClick={() => setAuthMode(isSignup ? "login" : "signup")} className="mt-5 font-bold underline">{isSignup ? "Already have an account? Login" : "New customer? Create account"}</button></div></div></motion.section>;
}
function AdminLoginRequired({ setView, setAuthMode }) { return <motion.section initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mx-auto min-h-[70vh] max-w-3xl px-4 py-20 text-center"><div className="rounded-[2rem] border border-[#d4c7b6] bg-white p-10 shadow-xl"><ShieldCheck className="mx-auto h-14 w-14" /><h2 className="mt-5 font-serif text-4xl font-black">Admin login required</h2><p className="mt-3 text-[#5f5349]">Admin panel open karne ke liye email aur password zaroori hai.</p><p className="mt-4 rounded-2xl bg-[#f8f4ee] p-4 text-sm"><b>Email:</b> {adminEmail}<br /><b>Password:</b> {adminPassword}</p><button onClick={() => { setAuthMode("login"); setView("auth"); }} className="mt-6 rounded-full bg-[#171411] px-7 py-4 font-bold text-white">Login as Admin</button></div></motion.section>; }

function Hero({ setView }) { return <section className="mx-auto grid min-h-[84vh] max-w-7xl items-center gap-10 px-4 py-16 lg:grid-cols-2"><motion.div initial={{ y: 28, opacity: 0 }} animate={{ y: 0, opacity: 1 }}><p className="mb-5 text-sm font-bold uppercase tracking-[0.35em] text-[#8b745d]">Classic luxury collection</p><h2 className="font-serif text-5xl font-black leading-tight md:text-7xl">Timeless fashion for modern shopping.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#5f5349]">Professional eCommerce UI with login, signup, admin password, working cart, customer address, contact form, product management, and revenue dashboard.</p><div className="mt-8 flex flex-wrap gap-4"><button onClick={() => setView("auth")} className="rounded-full bg-[#171411] px-8 py-4 font-bold text-white transition hover:scale-105">Login / Signup</button><a href="#video" className="rounded-full border border-[#171411] px-8 py-4 font-bold transition hover:bg-white">Watch Video</a></div></motion.div><motion.div initial={{ scale: .94, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="relative"><div className="overflow-hidden rounded-[2rem] border border-[#d4c7b6] bg-white p-3 shadow-2xl"><img className="h-[560px] w-full rounded-[1.5rem] object-cover" src="https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1100&q=80" alt="Classic fashion" /></div><div className="absolute -bottom-6 left-8 right-8 rounded-3xl border border-[#d4c7b6] bg-white p-5 shadow-xl"><p className="text-xs uppercase tracking-[0.25em] text-[#8b745d]">New arrival</p><div className="mt-2 flex items-center justify-between"><h3 className="font-serif text-2xl font-black">The Classic Edit</h3><p className="font-black">From $120</p></div></div></motion.div></section>; }
function TrustBar() { const items = [[ShieldCheck,"Secure Login"],[Truck,"Fast Delivery"],[CreditCard,"Multiple Payments"],[User,"Customer Profile"]]; return <section className="mx-auto grid max-w-7xl grid-cols-2 gap-3 px-4 py-8 md:grid-cols-4">{items.map(([Icon,text]) => <div key={text} className="flex items-center gap-3 rounded-2xl border border-[#d4c7b6] bg-white p-5 shadow-sm"><Icon className="h-5 w-5"/><span className="font-bold">{text}</span></div>)}</section>; }
function VideoSection() { return <section id="video" className="mx-auto max-w-7xl px-4 py-16"><SectionTitle eyebrow="Brand film" title="Video showcase section" /><div className="grid gap-6 lg:grid-cols-[1.4fr_.8fr]"><div className="relative overflow-hidden rounded-[2rem] border border-[#d4c7b6] bg-white p-3 shadow-xl"><video className="h-[420px] w-full rounded-[1.5rem] object-cover" autoPlay loop muted playsInline poster="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80"><source src="https://videos.pexels.com/video-files/853915/853915-hd_1920_1080_25fps.mp4" type="video/mp4" /></video><div className="absolute inset-3 grid place-items-center rounded-[1.5rem] bg-black/10"><div className="grid h-20 w-20 place-items-center rounded-full bg-white/90 shadow-xl"><Play className="h-8 w-8 fill-[#171411]" /></div></div></div><div className="rounded-[2rem] border border-[#d4c7b6] bg-white p-8 shadow-sm"><p className="text-sm font-bold uppercase tracking-[0.25em] text-[#8b745d]">Campaign video</p><h3 className="mt-4 font-serif text-4xl font-black">Show products with premium motion.</h3><p className="mt-4 leading-7 text-[#5f5349]">Add your product video, brand story, sale campaign, or model shoot here.</p><button className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#171411] px-6 py-4 font-bold text-white">View Campaign <ArrowRight className="h-4 w-4" /></button></div></div></section>; }
function Collections() { const data = [["Women Collection","https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80"],["Men Collection","https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=900&q=80"],["Accessories","https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80"]]; return <section className="mx-auto max-w-7xl px-4 py-16"><SectionTitle eyebrow="Collections" title="Classic categories"/><div className="grid gap-5 md:grid-cols-3">{data.map(([title,img]) => <motion.div whileHover={{y:-8}} key={title} className="overflow-hidden rounded-[2rem] border border-[#d4c7b6] bg-white p-3 shadow-sm"><img src={img} alt={title} className="h-80 w-full rounded-[1.5rem] object-cover"/><div className="p-5"><h3 className="font-serif text-3xl font-black">{title}</h3><p className="mt-2 text-[#6e6257]">Elegant product category layout.</p></div></motion.div>)}</div></section>; }
function Shop({ products, activeCategory, setActiveCategory, query, setQuery, addToCart, toggleWishlist, wishlist }) { return <section className="mx-auto max-w-7xl px-4 py-16"><SectionTitle eyebrow="Shop" title="Products with working cart"/><div className="mb-8 flex flex-col gap-4 rounded-2xl border border-[#d4c7b6] bg-white p-4 shadow-sm md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-2">{categories.map(cat => <button key={cat} onClick={() => setActiveCategory(cat)} className={`rounded-full px-5 py-3 text-sm font-bold ${activeCategory===cat?"bg-[#171411] text-white":"bg-[#f8f4ee] hover:bg-[#eee5d9]"}`}>{cat}</button>)}</div><div className="flex items-center gap-2 rounded-full border border-[#d4c7b6] bg-[#f8f4ee] px-4 py-3"><Search className="h-4 w-4 text-[#8b745d]"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search products..." className="w-full bg-transparent text-sm outline-none md:w-64"/></div></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.map(product => <ProductCard key={product.id} product={product} addToCart={addToCart} toggleWishlist={toggleWishlist} liked={wishlist.some(i=>i.id===product.id)} />)}</div></section>; }
function ProductCard({ product, addToCart, toggleWishlist, liked }) { return <motion.article layout whileHover={{y:-8}} className="overflow-hidden rounded-[2rem] border border-[#d4c7b6] bg-white p-3 shadow-sm"><div className="relative h-80 overflow-hidden rounded-[1.5rem]"><img src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-700 hover:scale-110"/><span className="absolute left-4 top-4 rounded-full bg-white px-4 py-2 text-xs font-black">{product.badge}</span><button onClick={()=>toggleWishlist(product)} className={`absolute right-4 top-4 rounded-full p-3 shadow ${liked?"bg-[#171411] text-white":"bg-white"}`}><Heart className="h-4 w-4" fill={liked?"currentColor":"none"}/></button></div><div className="p-4"><div className="mb-2 flex items-center justify-between"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#8b745d]">{product.category}</p><p className="flex items-center gap-1 text-sm font-bold"><Star className="h-4 w-4 fill-[#171411]"/> {product.rating}</p></div><h3 className="font-serif text-2xl font-black">{product.name}</h3><p className="mt-2 text-sm text-[#6e6257]">Sizes S-XL · Stock {product.stock}</p><div className="mt-5 flex items-end justify-between gap-4"><div><p className="text-2xl font-black">{currency(product.price)}</p><p className="text-sm text-[#9a8d80] line-through">{currency(product.oldPrice)}</p></div><button onClick={()=>addToCart(product)} className="rounded-full bg-[#171411] px-5 py-3 text-sm font-bold text-white">Add to Cart</button></div></div></motion.article>; }
function CartPage({ cart, cartTotal, changeQty, removeFromCart, setView, customer }) { const shipping = cart.length ? 15 : 0, tax = cart.length ? Math.round(cartTotal * .08) : 0; return <motion.section initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mx-auto min-h-[80vh] max-w-7xl px-4 py-16"><SectionTitle eyebrow="Cart" title="Checkout with required address"/><div className="grid gap-6 lg:grid-cols-[1fr_420px]"><div className="space-y-4">{cart.length===0 ? <EmptyState setView={setView}/> : cart.map(item => <div key={item.id} className="flex flex-col gap-4 rounded-[2rem] border border-[#d4c7b6] bg-white p-4 shadow-sm sm:flex-row sm:items-center"><img src={item.image} alt={item.name} className="h-28 w-full rounded-3xl object-cover sm:w-28"/><div className="flex-1"><h3 className="font-serif text-2xl font-black">{item.name}</h3><p className="text-sm text-[#6e6257]">Size {item.size} · {item.color}</p><p className="mt-2 font-black">{currency(item.price)}</p></div><div className="flex items-center gap-2"><button onClick={()=>changeQty(item.id,-1)} className="rounded-full bg-[#f8f4ee] p-2"><Minus className="h-4 w-4"/></button><span className="w-8 text-center font-black">{item.qty}</span><button onClick={()=>changeQty(item.id,1)} className="rounded-full bg-[#f8f4ee] p-2"><Plus className="h-4 w-4"/></button></div><button onClick={()=>removeFromCart(item.id)} className="rounded-full bg-[#f8f4ee] p-3"><Trash2 className="h-4 w-4"/></button></div>)}</div><div className="space-y-5"><Panel title="Order Summary"><SummaryLine label="Subtotal" value={currency(cartTotal)}/><SummaryLine label="Shipping" value={currency(shipping)}/><SummaryLine label="Tax" value={currency(tax)}/><div className="my-5 h-px bg-[#ded4c5]"/><SummaryLine label="Total" value={currency(cartTotal+shipping+tax)} bold/><button className="mt-6 w-full rounded-full bg-[#171411] px-6 py-4 font-bold text-white">Checkout</button><button className="mt-3 w-full rounded-full border border-[#171411] px-6 py-4 font-bold">Cash on Delivery</button></Panel><Panel title="Delivery Address"><AddressPreview customer={customer}/></Panel></div></div></motion.section>; }
function CustomerDashboard({ wishlist, cart, customer, setCustomer, currentUser }) { const cards = [[Package,"Orders","12 orders"],[Heart,"Wishlist",`${wishlist.length} saved`],[ShoppingBag,"Cart",`${cart.length} items`],[User,"Profile",currentUser.email]]; return <motion.section initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mx-auto min-h-[80vh] max-w-7xl px-4 py-16"><SectionTitle eyebrow="Customer" title={`Welcome ${currentUser.name}`}/><DashboardGrid cards={cards}/><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_.9fr]"><CustomerProfileForm customer={customer} setCustomer={setCustomer}/><Panel title="Order Tracking"><Timeline/><div className="mt-6 rounded-2xl bg-[#f8f4ee] p-4"><h4 className="font-black">Address Preview</h4><AddressPreview customer={customer}/></div></Panel></div></motion.section>; }
function CustomerProfileForm({ customer, setCustomer }) { const fields = [["name","Full Name *"],["email","Email Address *"],["phone","Phone Number *"],["city","City *"],["area","Area / Town *"],["street","Complete Street Address *"],["zip","Zip / Postal Code *"],["country","Country *"]]; return <Panel title="Profile Details"><div className="grid gap-4 sm:grid-cols-2">{fields.map(([key,label]) => <label key={key} className="block"><span className="mb-2 block text-sm font-bold text-[#6e6257]">{label}</span><input required value={customer[key]} onChange={(e)=>setCustomer({...customer,[key]:e.target.value})} className="w-full rounded-2xl border border-[#d4c7b6] bg-[#f8f4ee] px-4 py-3 outline-none focus:border-[#171411]" /></label>)}</div><button className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#171411] px-6 py-3 font-bold text-white"><Save className="h-4 w-4"/> Save Profile</button></Panel>; }
function AddressPreview({ customer }) { return <div className="mt-3 space-y-2 text-[#5f5349]"><p><b>Name:</b> {customer.name}</p><p><b>Email:</b> {customer.email}</p><p><b>Phone:</b> {customer.phone}</p><p><b>Address:</b> {customer.street}, {customer.area}, {customer.city}, {customer.zip}, {customer.country}</p></div>; }
function AdminDashboard({ products, deleteProduct, addProduct, revenue, customer }) { const [tab,setTab] = useState("revenue"); const cards = [[DollarSign,"Revenue",currency(revenue)],[Package,"Products",products.length],[Users,"Customers","48,200"],[ClipboardList,"Orders","326"]]; return <motion.section initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mx-auto min-h-[80vh] max-w-7xl px-4 py-16"><SectionTitle eyebrow="Admin" title="Admin panel with email/password access"/><div className="mb-6 rounded-2xl border border-[#d4c7b6] bg-white p-4 font-bold shadow-sm">Logged in admin: {adminEmail}</div><DashboardGrid cards={cards}/><div className="mt-6 flex flex-wrap gap-2">{[["revenue","Revenue Dashboard"],["add","Add Product"],["products","Manage Products"],["customers","Customer Details"]].map(([id,label]) => <button key={id} onClick={()=>setTab(id)} className={`rounded-full px-5 py-3 font-bold ${tab===id?"bg-[#171411] text-white":"bg-white border border-[#d4c7b6]"}`}>{label}</button>)}</div><div className="mt-6">{tab==="revenue" && <RevenueDashboard revenue={revenue}/>} {tab==="add" && <AddProductForm addProduct={addProduct}/>} {tab==="products" && <ManageProducts products={products} deleteProduct={deleteProduct}/>} {tab==="customers" && <CustomerAdminView customer={customer}/>}</div></motion.section>; }
function RevenueDashboard({ revenue }) { return <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><Panel title="Monthly Revenue Chart"><div className="flex h-80 items-end gap-3">{[45,70,38,90,62,100,78,85,55,95,74,110].map((h,i)=><div key={i} className="flex-1 rounded-t-2xl bg-[#171411]" style={{height:`${h*2}px`}} />)}</div></Panel><Panel title="Revenue Details"><SummaryLine label="Gross Revenue" value={currency(revenue)} /><SummaryLine label="Shipping Income" value="$4,890" /><SummaryLine label="Discounts" value="-$1,240" /><SummaryLine label="Net Profit" value={currency(Math.round(revenue*.62))} bold /></Panel></div>; }
function AddProductForm({ addProduct }) { const [form,setForm]=useState({name:"",category:"Women",price:"",stock:"",badge:"New",image:"https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80"}); const submit=(e)=>{e.preventDefault(); if(!form.name||!form.price||!form.stock||!form.image) return alert("Please fill all required product details"); addProduct(form); setForm({...form,name:"",price:"",stock:""});}; return <Panel title="Add New Product"><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><Input label="Product Name *" value={form.name} onChange={(v)=>setForm({...form,name:v})}/><label><span className="mb-2 block text-sm font-bold text-[#6e6257]">Category *</span><select value={form.category} onChange={(e)=>setForm({...form,category:e.target.value})} className="w-full rounded-2xl border border-[#d4c7b6] bg-[#f8f4ee] px-4 py-3 outline-none">{categories.filter(c=>c!=="All").map(c=><option key={c}>{c}</option>)}</select></label><Input label="Price *" type="number" value={form.price} onChange={(v)=>setForm({...form,price:v})}/><Input label="Stock Quantity *" type="number" value={form.stock} onChange={(v)=>setForm({...form,stock:v})}/><Input label="Badge" value={form.badge} onChange={(v)=>setForm({...form,badge:v})}/><Input label="Image URL *" value={form.image} onChange={(v)=>setForm({...form,image:v})}/><button className="md:col-span-2 inline-flex items-center justify-center gap-2 rounded-full bg-[#171411] px-6 py-4 font-bold text-white"><Plus className="h-4 w-4"/> Add Product</button></form></Panel>; }
function ManageProducts({ products, deleteProduct }) { return <Panel title="Manage Products"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-[#d4c7b6]"><th className="p-3">Image</th><th className="p-3">Name</th><th className="p-3">Category</th><th className="p-3">Price</th><th className="p-3">Stock</th><th className="p-3">Action</th></tr></thead><tbody>{products.map(p=><tr key={p.id} className="border-b border-[#eee5d9]"><td className="p-3"><img src={p.image} alt={p.name} className="h-14 w-14 rounded-xl object-cover"/></td><td className="p-3 font-bold">{p.name}</td><td className="p-3">{p.category}</td><td className="p-3">{currency(p.price)}</td><td className="p-3">{p.stock}</td><td className="p-3"><button onClick={()=>deleteProduct(p.id)} className="rounded-full bg-red-100 px-4 py-2 font-bold text-red-700"><Trash2 className="inline h-4 w-4"/> Delete</button></td></tr>)}</tbody></table></div></Panel>; }
function CustomerAdminView({ customer }) { return <Panel title="Customer Profile & Necessary Address Details"><div className="grid gap-4 md:grid-cols-2"><Info label="Full Name" value={customer.name}/><Info label="Email" value={customer.email}/><Info label="Phone" value={customer.phone}/><Info label="City" value={customer.city}/><Info label="Area" value={customer.area}/><Info label="Street Address" value={customer.street}/><Info label="Zip Code" value={customer.zip}/><Info label="Country" value={customer.country}/></div></Panel>; }
function ContactSection({ customer }) { return <section className="mx-auto max-w-7xl px-4 py-16"><SectionTitle eyebrow="Contact" title="Contact, email and address section"/><div className="grid gap-6 lg:grid-cols-2"><Panel title="Send Message"><div className="grid gap-4"><input className="rounded-2xl border border-[#d4c7b6] bg-[#f8f4ee] px-4 py-3 outline-none" placeholder="Your name" defaultValue={customer.name}/><input className="rounded-2xl border border-[#d4c7b6] bg-[#f8f4ee] px-4 py-3 outline-none" placeholder="Email address" defaultValue={customer.email}/><textarea className="min-h-32 rounded-2xl border border-[#d4c7b6] bg-[#f8f4ee] px-4 py-3 outline-none" placeholder="Write your message..."/><button className="inline-flex items-center justify-center gap-2 rounded-full bg-[#171411] px-6 py-4 font-bold text-white"><Send className="h-4 w-4"/> Send Email</button></div></Panel><Panel title="Store Details"><p className="flex items-center gap-3 text-[#5f5349]"><Mail/> support@aurelia.com</p><p className="mt-4 flex items-center gap-3 text-[#5f5349]"><Phone/> +92 300 0000000</p><p className="mt-4 flex items-center gap-3 text-[#5f5349]"><MapPin/> Civil Lines, Jhang, Pakistan</p><p className="mt-6 rounded-2xl bg-[#f8f4ee] p-4 text-[#5f5349]">Required checkout address: full name, phone, email, city, area, street address, zip code, and country.</p></Panel></div></section>; }
function ClassicBanner(){return <section className="mx-auto max-w-7xl px-4 py-16"><div className="grid overflow-hidden rounded-[2rem] border border-[#d4c7b6] bg-white shadow-sm lg:grid-cols-2"><img src="https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1100&q=80" alt="Store banner" className="h-full min-h-[420px] w-full object-cover"/><div className="p-10 md:p-14"><p className="text-sm font-bold uppercase tracking-[0.25em] text-[#8b745d]">Special offer</p><h2 className="mt-4 font-serif text-5xl font-black">Elegant sale campaign section.</h2><p className="mt-5 leading-8 text-[#5f5349]">Coupons, shipping, tax, Stripe, PayPal, COD, and order tracking layout included.</p><button className="mt-8 rounded-full bg-[#171411] px-7 py-4 font-bold text-white">Explore Sale</button></div></div></section>}
function Testimonials(){return <section className="mx-auto max-w-7xl px-4 py-16"><SectionTitle eyebrow="Reviews" title="Customer testimonials"/><div className="grid gap-5 md:grid-cols-3">{["Clean and classic design.","Products look premium and real.","Dashboard is easy to understand."].map((q,i)=><div key={q} className="rounded-[2rem] border border-[#d4c7b6] bg-white p-7 shadow-sm"><div className="mb-4 flex">{Array.from({length:5}).map((_,n)=><Star key={n} className="h-4 w-4 fill-[#171411]"/>)}</div><p className="font-serif text-2xl font-black">“{q}”</p><p className="mt-4 text-sm text-[#6e6257]">Verified customer #{i+1}</p></div>)}</div></section>}
function Newsletter(){return <section className="mx-auto max-w-7xl px-4 py-16"><div className="rounded-[2rem] border border-[#d4c7b6] bg-white p-10 text-center shadow-sm"><h2 className="font-serif text-5xl font-black">Join our newsletter</h2><p className="mx-auto mt-4 max-w-2xl text-[#5f5349]">Get new arrivals, sale updates, blog posts, and discount codes.</p><div className="mx-auto mt-7 flex max-w-xl flex-col gap-3 rounded-full border border-[#d4c7b6] bg-[#f8f4ee] p-2 sm:flex-row"><input className="flex-1 bg-transparent px-5 py-3 outline-none" placeholder="Enter your email"/><button className="rounded-full bg-[#171411] px-7 py-3 font-bold text-white">Subscribe</button></div></div></section>}
function DashboardGrid({ cards }){return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([Icon,title,text])=><div key={title} className="rounded-[2rem] border border-[#d4c7b6] bg-white p-6 shadow-sm"><Icon className="mb-4 h-7 w-7"/><h3 className="font-serif text-3xl font-black">{title}</h3><p className="text-[#6e6257]">{text}</p></div>)}</div>}
function Panel({title,children}){return <div className="rounded-[2rem] border border-[#d4c7b6] bg-white p-7 shadow-sm"><h3 className="mb-5 font-serif text-3xl font-black">{title}</h3>{children}</div>}
function Timeline(){return <div className="space-y-4">{["Order placed","Payment verified","Packed","Out for delivery"].map((item,i)=><div key={item} className="flex gap-4"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#171411] text-sm font-black text-white">{i+1}</div><div><p className="font-black">{item}</p><p className="text-sm text-[#6e6257]">Live order update</p></div></div>)}</div>}
function EmptyState({setView}){return <div className="rounded-[2rem] border border-[#d4c7b6] bg-white p-10 text-center shadow-sm"><ShoppingBag className="mx-auto h-12 w-12"/><h3 className="mt-4 font-serif text-3xl font-black">Your cart is empty</h3><p className="mt-2 text-[#6e6257]">Add products to start checkout.</p><button onClick={()=>setView("home")} className="mt-6 rounded-full bg-[#171411] px-6 py-3 font-bold text-white">Start Shopping</button></div>}
function SummaryLine({label,value,bold}){return <div className={`mt-4 flex items-center justify-between ${bold?"text-xl font-black":"font-semibold text-[#5f5349]"}`}><span>{label}</span><span>{value}</span></div>}
function SectionTitle({eyebrow,title}){return <div className="mb-8"><p className="mb-2 text-sm font-bold uppercase tracking-[0.3em] text-[#8b745d]">{eyebrow}</p><h2 className="max-w-3xl font-serif text-4xl font-black tracking-tight md:text-5xl">{title}</h2></div>}
function Input({label,value,onChange,type="text"}) { return <label><span className="mb-2 block text-sm font-bold text-[#6e6257]">{label}</span><input type={type} value={value} onChange={(e)=>onChange(e.target.value)} className="w-full rounded-2xl border border-[#d4c7b6] bg-[#f8f4ee] px-4 py-3 outline-none focus:border-[#171411]" /></label>; }
function Info({label,value}) { return <div className="rounded-2xl bg-[#f8f4ee] p-4"><p className="text-sm font-bold text-[#8b745d]">{label}</p><p className="mt-1 font-black">{value}</p></div>; }
function Footer(){return <footer className="mt-16 border-t border-[#d4c7b6] bg-white px-4 py-12"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-4"><div><div className="flex items-center gap-3"><img src={logoImage} alt="Store logo" className="h-12 w-12 rounded-full object-cover"/><h3 className="font-serif text-2xl font-black">AURELIA</h3></div><p className="mt-4 text-[#6e6257]">Classic full-stack eCommerce store.</p></div><div><h4 className="font-black">Pages</h4><p className="mt-3 text-[#6e6257]">About · Contact · FAQ · Blog</p></div><div><h4 className="font-black">Policies</h4><p className="mt-3 text-[#6e6257]">Privacy · Terms · Shipping · Returns</p></div><div><h4 className="font-black">Contact</h4><p className="mt-3 flex items-center gap-2 text-[#6e6257]"><Mail className="h-4 w-4"/> support@aurelia.com</p><p className="mt-2 flex items-center gap-2 text-[#6e6257]"><Phone className="h-4 w-4"/> +92 300 0000000</p><p className="mt-2 flex items-center gap-2 text-[#6e6257]"><MapPin className="h-4 w-4"/> Civil Lines, Jhang</p></div></div></footer>}
